import { useState, useEffect, useRef } from 'react';
import { useQuery, useMutation } from '@tanstack/react-query';
import api from '../api/axios';

// ─── Setup screen ─────────────────────────────────────────────────────────────
function QuizSetup({ onStart }) {
  const [form, setForm] = useState({ topicId: '', count: 10, difficulty: 'medium' });
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const { data: plans } = useQuery({
    queryKey: ['plans'],
    queryFn: () => api.get('/plans').then(r => r.data.plans),
  });

  const { data: topics } = useQuery({
    queryKey: ['topics', plans?.[0]?._id],
    queryFn: () => api.get(`/plans/${plans[0]._id}/topics`).then(r => r.data.topics),
    enabled: !!plans?.[0]?._id,
  });

  const handleStart = async () => {
    if (!form.topicId) { setError('Please select a topic'); return; }
    setLoading(true);
    setError('');
    try {
      const { data } = await api.post('/quiz/generate', form);
      onStart(data.quiz);
    } catch (err) {
      setError(err.response?.data?.message || 'Failed to generate quiz. Try again.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="max-w-lg mx-auto">
      <div className="text-center mb-8">
        <p className="text-5xl mb-3">🧠</p>
        <h1 className="text-2xl font-bold">Mock Test</h1>
        <p className="text-gray-400 text-sm mt-1">AI-generated MCQs based on your topics</p>
      </div>

      <div className="card flex flex-col gap-5">
        {error && (
          <div className="bg-rose-500/10 border border-rose-500/20 text-rose-400 text-sm px-4 py-3 rounded-lg">
            {error}
          </div>
        )}

        <div>
          <label className="text-xs text-gray-400 block mb-1">Select topic</label>
          <select
            value={form.topicId}
            onChange={e => setForm(f => ({ ...f, topicId: e.target.value }))}
            className="w-full bg-gray-800 border border-gray-700 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:border-primary-500"
          >
            <option value="">— Choose a topic —</option>
            {topics?.map(t => (
              <option key={t._id} value={t._id}>{t.name} ({t.subject})</option>
            ))}
          </select>
        </div>

        <div>
          <label className="text-xs text-gray-400 block mb-1">
            Number of questions: <span className="text-primary-400 font-semibold">{form.count}</span>
          </label>
          <input
            type="range" min="5" max="20" step="5"
            value={form.count}
            onChange={e => setForm(f => ({ ...f, count: parseInt(e.target.value) }))}
            className="w-full accent-indigo-500"
          />
          <div className="flex justify-between text-xs text-gray-600 mt-1">
            <span>5</span><span>10</span><span>15</span><span>20</span>
          </div>
        </div>

        <div>
          <label className="text-xs text-gray-400 block mb-2">Difficulty</label>
          <div className="flex gap-2">
            {['easy', 'medium', 'hard'].map(d => (
              <button
                key={d}
                onClick={() => setForm(f => ({ ...f, difficulty: d }))}
                className={`flex-1 py-2 rounded-lg text-sm font-medium capitalize transition-colors ${
                  form.difficulty === d
                    ? d === 'easy' ? 'bg-green-600 text-white'
                      : d === 'medium' ? 'bg-amber-600 text-white'
                      : 'bg-rose-600 text-white'
                    : 'bg-gray-800 text-gray-400 hover:bg-gray-700'
                }`}
              >
                {d}
              </button>
            ))}
          </div>
        </div>

        <button
          onClick={handleStart}
          disabled={loading}
          className="btn-primary py-3 text-base font-semibold"
        >
          {loading ? (
            <span className="flex items-center justify-center gap-2">
              <span className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
              Generating questions...
            </span>
          ) : '🚀 Start Quiz'}
        </button>

        <p className="text-xs text-gray-500 text-center">
          Questions are generated by AI based on your topic. May take 5-10 seconds.
        </p>
      </div>
    </div>
  );
}

// ─── Quiz screen ──────────────────────────────────────────────────────────────
function QuizScreen({ quiz, onFinish }) {
  const [currentIdx, setCurrentIdx] = useState(0);
  const [answers, setAnswers] = useState({});
  const [selected, setSelected] = useState(null);
  const [revealed, setRevealed] = useState(false);
  const [timeLeft, setTimeLeft] = useState(quiz.questions.length * 60); // 1 min per question
  const intervalRef = useRef(null);

  const question = quiz.questions[currentIdx];
  const isLast = currentIdx === quiz.questions.length - 1;

  // Timer
  useEffect(() => {
    intervalRef.current = setInterval(() => {
      setTimeLeft(t => {
        if (t <= 1) {
          clearInterval(intervalRef.current);
          handleFinish();
          return 0;
        }
        return t - 1;
      });
    }, 1000);
    return () => clearInterval(intervalRef.current);
  }, []);

  const formatTime = (s) => `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;

  const handleSelect = (idx) => {
    if (revealed) return;
    setSelected(idx);
  };

  const handleReveal = () => {
    if (selected === null) return;
    setAnswers(a => ({ ...a, [currentIdx]: selected }));
    setRevealed(true);
  };

  const handleNext = () => {
    if (!revealed && selected !== null) {
      setAnswers(a => ({ ...a, [currentIdx]: selected }));
    }
    setSelected(null);
    setRevealed(false);
    setCurrentIdx(i => i + 1);
  };

  const handleFinish = () => {
    clearInterval(intervalRef.current);
    const finalAnswers = { ...answers };
    if (selected !== null) finalAnswers[currentIdx] = selected;
    const score = quiz.questions.reduce((s, q, i) => s + (finalAnswers[i] === q.correctIndex ? 1 : 0), 0);
    onFinish(score, quiz.questions.length, finalAnswers);
  };

  const optionStyle = (idx) => {
    if (!revealed) {
      return selected === idx
        ? 'border-primary-500 bg-primary-500/10 text-white'
        : 'border-gray-700 hover:border-gray-500 text-gray-300';
    }
    if (idx === question.correctIndex) return 'border-green-500 bg-green-500/10 text-green-300';
    if (idx === selected && idx !== question.correctIndex) return 'border-rose-500 bg-rose-500/10 text-rose-300';
    return 'border-gray-700 text-gray-500';
  };

  const timerColor = timeLeft < 60 ? 'text-rose-400' : timeLeft < 120 ? 'text-amber-400' : 'text-gray-300';

  return (
    <div className="max-w-2xl mx-auto">
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <div>
          <p className="text-sm font-medium">{quiz.topicName}</p>
          <p className="text-xs text-gray-400">{quiz.subject} · {quiz.difficulty}</p>
        </div>
        <div className={`font-mono font-bold text-lg ${timerColor}`}>
          ⏱ {formatTime(timeLeft)}
        </div>
      </div>

      {/* Progress bar */}
      <div className="w-full bg-gray-800 rounded-full h-1.5 mb-6">
        <div
          className="bg-primary-500 h-1.5 rounded-full transition-all"
          style={{ width: `${((currentIdx + 1) / quiz.questions.length) * 100}%` }}
        />
      </div>

      {/* Question */}
      <div className="card mb-4">
        <div className="flex items-start gap-3 mb-5">
          <span className="bg-primary-600 text-white text-xs font-bold px-2.5 py-1 rounded-lg shrink-0">
            Q{currentIdx + 1}/{quiz.questions.length}
          </span>
          <p className="font-medium leading-relaxed">{question.question}</p>
        </div>

        {/* Options */}
        <div className="flex flex-col gap-2">
          {question.options.map((opt, idx) => (
            <button
              key={idx}
              onClick={() => handleSelect(idx)}
              className={`w-full text-left px-4 py-3 rounded-xl border-2 text-sm transition-all ${optionStyle(idx)}`}
            >
              <span className="font-semibold mr-2">{['A','B','C','D'][idx]}.</span>
              {opt}
            </button>
          ))}
        </div>

        {/* Explanation */}
        {revealed && (
          <div className="mt-4 p-3 bg-blue-500/10 border border-blue-500/20 rounded-xl">
            <p className="text-xs text-blue-300">
              <span className="font-semibold">Explanation: </span>
              {question.explanation}
            </p>
          </div>
        )}
      </div>

      {/* Controls */}
      <div className="flex gap-3">
        {!revealed ? (
          <button
            onClick={handleReveal}
            disabled={selected === null}
            className="btn-primary flex-1 py-2.5 disabled:opacity-40 disabled:cursor-not-allowed"
          >
            Check answer
          </button>
        ) : isLast ? (
          <button onClick={handleFinish} className="btn-primary flex-1 py-2.5">
            Finish quiz →
          </button>
        ) : (
          <button onClick={handleNext} className="btn-primary flex-1 py-2.5">
            Next question →
          </button>
        )}

        {!revealed && !isLast && (
          <button onClick={handleNext} className="btn-ghost px-4 py-2.5 text-sm">
            Skip
          </button>
        )}
      </div>
    </div>
  );
}

// ─── Results screen ───────────────────────────────────────────────────────────
function ResultsScreen({ quiz, score, total, answers, onRetry, onExit }) {
  const pct = Math.round((score / total) * 100);
  const [submitted, setSubmitted] = useState(false);

  const submit = useMutation({
    mutationFn: () => api.post('/quiz/submit', { topicId: quiz.topicId, score, total }),
    onSuccess: () => setSubmitted(true),
  });

  useEffect(() => { submit.mutate(); }, []);

  const resultColor = pct >= 80 ? 'text-green-400' : pct >= 60 ? 'text-amber-400' : 'text-rose-400';
  const resultMsg   = pct >= 80 ? '🎉 Excellent!' : pct >= 60 ? '👍 Good job!' : '📚 Keep practicing!';

  return (
    <div className="max-w-2xl mx-auto">
      {/* Score */}
      <div className="card text-center mb-6 py-8">
        <p className="text-5xl mb-2">{pct >= 80 ? '🏆' : pct >= 60 ? '⭐' : '💪'}</p>
        <p className={`text-4xl font-bold mb-1 ${resultColor}`}>{pct}%</p>
        <p className="text-lg font-semibold mb-1">{resultMsg}</p>
        <p className="text-gray-400 text-sm">{score} out of {total} correct</p>
        {submitted && (
          <p className="text-xs text-primary-400 mt-3">✅ Confidence score updated for {quiz.topicName}</p>
        )}
      </div>

      {/* Review answers */}
      <h3 className="font-semibold mb-3">Review answers</h3>
      <div className="flex flex-col gap-3 mb-6">
        {quiz.questions.map((q, i) => {
          const userAnswer = answers[i];
          const correct = userAnswer === q.correctIndex;
          return (
            <div key={i} className={`card border ${correct ? 'border-green-500/30' : 'border-rose-500/30'}`}>
              <div className="flex items-start gap-2 mb-2">
                <span>{correct ? '✅' : '❌'}</span>
                <p className="text-sm font-medium">{q.question}</p>
              </div>
              <p className="text-xs text-green-400 ml-6">
                Correct: {q.options[q.correctIndex]}
              </p>
              {!correct && userAnswer !== undefined && (
                <p className="text-xs text-rose-400 ml-6">
                  Your answer: {q.options[userAnswer]}
                </p>
              )}
              <p className="text-xs text-gray-500 ml-6 mt-1">{q.explanation}</p>
            </div>
          );
        })}
      </div>

      {/* Actions */}
      <div className="flex gap-3">
        <button onClick={onRetry} className="btn-primary flex-1 py-2.5">Try again</button>
        <button onClick={onExit}  className="btn-ghost flex-1 py-2.5">Back to topics</button>
      </div>
    </div>
  );
}

// ─── Main Quiz page ───────────────────────────────────────────────────────────
export default function Quiz() {
  const [stage, setStage] = useState('setup'); // 'setup' | 'quiz' | 'results'
  const [quiz, setQuiz] = useState(null);
  const [results, setResults] = useState(null);

  const handleStart = (quizData) => {
    setQuiz(quizData);
    setStage('quiz');
  };

  const handleFinish = (score, total, answers) => {
    setResults({ score, total, answers });
    setStage('results');
  };

  const handleRetry = () => {
    setResults(null);
    setStage('setup');
  };

  return (
    <div className="max-w-4xl mx-auto px-4 py-8">
      {stage === 'setup' && <QuizSetup onStart={handleStart} />}
      {stage === 'quiz' && quiz && (
        <QuizScreen quiz={quiz} onFinish={handleFinish} />
      )}
      {stage === 'results' && quiz && results && (
        <ResultsScreen
          quiz={quiz}
          score={results.score}
          total={results.total}
          answers={results.answers}
          onRetry={handleRetry}
          onExit={handleRetry}
        />
      )}
    </div>
  );
}